modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="vanilla_plus_ore_pack"
version="1.0.0"
displayName="Vanilla Plus Ore Pack"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="polar, MCreator"

[[dependencies.vanilla_plus_ore_pack]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




